name: CrashClaim
version: ${version}
description: A modern advanced user oriented claiming system
author: Chasewhip
softdepend: [Vault, GriefPrevention, WorldGuard, PlaceholderAPI, Multiverse-Core, Hyperverse, LuckPerms ]
main: net.crashcraft.crashclaim.CrashClaim
api-version: 1.16